// { // STOP
//   symbol: 'BTCUSDT',
//   clientOrderId: 'x-15PC4ZJy8nE4D-0iptiEBvXEALHNK3',
//   orderSide: 'SELL',
//   orderType: 'LIMIT',
//   timeInForce: 'GTC',
//   originalQuantity: 0.001,
//   originalPrice: 103508.7,
//   averagePrice: 103508.7,
//   stopPrice: 0,
//   executionType: 'TRADE',
//   orderStatus: 'FILLED',
//   orderId: 8850365284,
//   lastFilledQuantity: 0.001,
//   orderFilledAccumulatedQuantity: 0.001,
//   lastFilledPrice: 103508.7,
//   commissionAmount: 0.02070174,
//   commissionAsset: 'USDT',
//   orderTradeTime: 1762435544251,
//   tradeId: 405072038,
//   bidsNotional: 0,
//   asksNotional: 0,
//   isMakerTrade: true,
//   isReduceOnly: true,
//   stopPriceWorkingType: 'CONTRACT_PRICE',
//   originalOrderType: 'LIMIT',
//   positionSide: 'LONG',
//   isCloseAll: false,
//   realisedProfit: 0.0265,
//   pP: false,
//   strategyId: 0,
//   ss: 0,
//   selfTradePrevention: 'EXPIRE_MAKER',
//   priceMatch: 'NONE',
//   goodTillDate: 0
// }
// ORDER FILLED {
//   symbol: 'BTCUSDT',
//   side: 'BUY',
//   type: 'LIMIT',
//   price: 102670.3,
//   qty: 0.001
// }